stages:
- name: 构建
  steps:
  - publishImageConfig:
      dockerfilePath: ./dockerdemo/Dockerfile
      buildContext: .
      tag: dockerdemo/v1
      registry: registry.cn-hangzhou.aliyuncs.com
  when:
    event:
      include:
      - pull_request
timeout: 60
branch: {}
notification: {}
