stages:
- name: 构建
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: |-
        cd dockerdemo
        gradle clean build
  when:
    event:
      include:
      - pull_request
- name: 发布
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: dockerdemo
      pushRemote: true
      registry: registry.cn-hangzhou.aliyuncs.com
  when:
    event:
      include:
      - pull_request
timeout: 60
branch: {}
notification: {}
